#pragma once
#include "fa4.hpp"

/*
application icons mapping
*/

// sections
#define ICON_CONTAINER ICON_FA_CODEPEN
#define ICON_IMAGE ICON_FA_HDD_O

// actions
#define ICON_REFRESH ICON_FA_REFRESH
#define ICON_CANCEL ICON_FA_BAN
#define ICON_OK ICON_FA_CHECK
#define ICON_PLUS ICON_FA_PLUS
#define ICON_MINUS ICON_FA_MINUS
#define ICON_REMOVE ICON_FA_TRASH

#define ICON_START ICON_FA_PLAY
#define ICON_STOP ICON_FA_STOP
#define ICON_PAUSE ICON_FA_PAUSE
#define ICON_RESUME ICON_FA_STEP_BACKWARD
#define ICON_RESTART ICON_FA_RECYCLE
#define ICON_KILL ICON_FA_TIMES
